// Modules generated by src/lib/estudios-plugin.ts.

declare module "virtual:estudios" {
  import type { EstudioSummary } from "@/lib/estudios";
  /** Every post, newest first. */
  const estudios: EstudioSummary[];
  export default estudios;
}

declare module "virtual:estudios-search" {
  /** slug -> the post's unique words, normalized with normalizeSearch and space-separated. */
  const index: Record<string, string>;
  export default index;
}

declare module "*.md" {
  import type { Estudio } from "@/lib/estudios";
  const estudio: Estudio;
  export default estudio;
}
