/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LeerLibroCapRouteImport } from './routes/leer.$libro.$cap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LeerLibroCapRoute = LeerLibroCapRouteImport.update({
  id: '/leer/$libro/$cap',
  path: '/leer/$libro/$cap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/newsletter': typeof NewsletterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/leer/$libro/$cap': typeof LeerLibroCapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/newsletter': typeof NewsletterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/leer/$libro/$cap': typeof LeerLibroCapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/newsletter': typeof NewsletterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/leer/$libro/$cap': typeof LeerLibroCapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/buscar' | '/newsletter' | '/sitemap.xml' | '/leer/$libro/$cap'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/buscar' | '/newsletter' | '/sitemap.xml' | '/leer/$libro/$cap'
  id:
    | '__root__'
    | '/'
    | '/buscar'
    | '/newsletter'
    | '/sitemap.xml'
    | '/leer/$libro/$cap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscarRoute: typeof BuscarRoute
  NewsletterRoute: typeof NewsletterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LeerLibroCapRoute: typeof LeerLibroCapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leer/$libro/$cap': {
      id: '/leer/$libro/$cap'
      path: '/leer/$libro/$cap'
      fullPath: '/leer/$libro/$cap'
      preLoaderRoute: typeof LeerLibroCapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscarRoute: BuscarRoute,
  NewsletterRoute: NewsletterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LeerLibroCapRoute: LeerLibroCapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
