/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ApiBillingRouteImport } from './routes/api/billing'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiConsultaRouteImport } from './routes/api/consulta'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as LeerLibroCapRouteImport } from './routes/leer.$libro.$cap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingRoute = ApiBillingRouteImport.update({
  id: '/api/billing',
  path: '/api/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsultaRoute = ApiConsultaRouteImport.update({
  id: '/api/consulta',
  path: '/api/consulta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LeerLibroCapRoute = LeerLibroCapRouteImport.update({
  id: '/leer/$libro/$cap',
  path: '/leer/$libro/$cap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/newsletter': typeof NewsletterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/welcome': typeof WelcomeRoute
  '/api/billing': typeof ApiBillingRoute
  '/api/chat': typeof ApiChatRoute
  '/api/consulta': typeof ApiConsultaRoute
  '/api/history': typeof ApiHistoryRoute
  '/leer/$libro/$cap': typeof LeerLibroCapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/newsletter': typeof NewsletterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/welcome': typeof WelcomeRoute
  '/api/billing': typeof ApiBillingRoute
  '/api/chat': typeof ApiChatRoute
  '/api/consulta': typeof ApiConsultaRoute
  '/api/history': typeof ApiHistoryRoute
  '/leer/$libro/$cap': typeof LeerLibroCapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/newsletter': typeof NewsletterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/welcome': typeof WelcomeRoute
  '/api/billing': typeof ApiBillingRoute
  '/api/chat': typeof ApiChatRoute
  '/api/consulta': typeof ApiConsultaRoute
  '/api/history': typeof ApiHistoryRoute
  '/leer/$libro/$cap': typeof LeerLibroCapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buscar'
    | '/newsletter'
    | '/sitemap.xml'
    | '/welcome'
    | '/api/billing'
    | '/api/chat'
    | '/api/consulta'
    | '/api/history'
    | '/leer/$libro/$cap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buscar'
    | '/newsletter'
    | '/sitemap.xml'
    | '/welcome'
    | '/api/billing'
    | '/api/chat'
    | '/api/consulta'
    | '/api/history'
    | '/leer/$libro/$cap'
  id:
    | '__root__'
    | '/'
    | '/buscar'
    | '/newsletter'
    | '/sitemap.xml'
    | '/welcome'
    | '/api/billing'
    | '/api/chat'
    | '/api/consulta'
    | '/api/history'
    | '/leer/$libro/$cap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscarRoute: typeof BuscarRoute
  NewsletterRoute: typeof NewsletterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiBillingRoute: typeof ApiBillingRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiConsultaRoute: typeof ApiConsultaRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  LeerLibroCapRoute: typeof LeerLibroCapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing': {
      id: '/api/billing'
      path: '/api/billing'
      fullPath: '/api/billing'
      preLoaderRoute: typeof ApiBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/consulta': {
      id: '/api/consulta'
      path: '/api/consulta'
      fullPath: '/api/consulta'
      preLoaderRoute: typeof ApiConsultaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leer/$libro/$cap': {
      id: '/leer/$libro/$cap'
      path: '/leer/$libro/$cap'
      fullPath: '/leer/$libro/$cap'
      preLoaderRoute: typeof LeerLibroCapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscarRoute: BuscarRoute,
  NewsletterRoute: NewsletterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WelcomeRoute: WelcomeRoute,
  ApiBillingRoute: ApiBillingRoute,
  ApiChatRoute: ApiChatRoute,
  ApiConsultaRoute: ApiConsultaRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  LeerLibroCapRoute: LeerLibroCapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
